### ISSUE TITLE
Squash migrations to eliminate orphan dependencies

### ISSUE THREAD

**Issue by jsolly** [jsolly/awesome-django-blog#133]
#### Context 
The python packages filetype and ckeditor (version 4) remain in the requirements because they are used in older migrations. If migrations are squashed, we can remove them.

**Comment by freedompraise** [comment]
Is this still an issue ? @jsolly

**Comment by jsolly** [comment]
Yeah, I haven't found a way to squash the migrations...we are up to 40 migrations files.
https://github.com/jsolly/awesome-django-blog/tree/master/app/blog/migrations

**Comment by jsolly** [comment]
According to the [Django Docs](https://docs.djangoproject.com/en/4.2/topics/migrations/#squashing-migrations) it's okay to have hundreds of migrations, so I think we are doing pretty good at 40.

> You are encouraged to make migrations freely and not worry about how many you have; the migration code is optimized to deal with hundreds at a time without much slowdown. However, eventually you will want to move back from having several hundred migrations to just a few, and that’s where squashing comes in
