### ISSUE TITLE
Create Application Diagram

### ISSUE THREAD

**Issue by jsolly** [jsolly/awesome-django-blog#18]
#### Context 
It would be nice if there was some kind of UML application diagram for how blogthedata.com is structured in terms of classes/functions/etc

#### Current Behavior/Workaround
None

#### Ideal behavior
An editable diagram that can be easily shared.

#### Things to consider
Might want to use [Draw.io](https://app.diagrams.net) ?

**Comment by justin107d** [comment]
This is another popular django package that allows you to diagram out the models in urls that I think you may want to look at:  https://github.com/django-extensions/django-extensions

**Comment by jsolly** [comment]
Not gonna bother with this one for now.
