### ISSUE TITLE
Comment Formatting Issue: Multiple Lines Appearing as One Line

### ISSUE THREAD

**Issue by freedompraise** [jsolly/awesome-django-blog#347]
*Issue Description:*

**Steps to Reproduce:**

- Go to any blog post on the site
- Scroll down to the comments section and click on the "Add Comment" button.
- In the comment form, enter a comment with multiple lines. For example:
``` csharp 
Hello,
This is a test comment
with multiple lines.
```
- Submit the comment.
- Observe that the comment appears as a single line in the comments section.

**Expected Behavior:**
The comment should be displayed with the same formatting as entered in the comment form. Each line of the comment should be displayed as a separate paragraph, maintaining line breaks.

**Actual Behavior:**
The comment is displayed as a single line, with no line breaks. This makes the comment content difficult to read and understand.

**Comment by freedompraise** [comment]
Hi @jsolly

I'm having an issue with my Django comments system where comments are submitted as a single line instead of multiple lines. I've tried a few things to fix the issue, but I haven't found a solution yet.

***Here are some of the things I've tried:***

- Modifying the `CommentForm` to use a `TextInput` widget instead of a `Textarea` widget for the `content` field.
- Using `CKEditor5Field` for the `content` field in the `CommentForm`.

None of these solutions have worked so far. Do you have any suggestions on how I can fix this issue?

Thanks

**Comment by jsolly** [comment]
All we needed was one more django template filter, [linebreaksbr](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#linebreaksbr)
```html
 <div class="comment-content">{{ comment.content|safe|linebreaksbr }}</div>
 ```

This is because html treats `\n` as whitespace. This template filter will replace all newlines with `<br>` tags to properly do new lines.

See https://github.com/jsolly/awesome-django-blog/commit/6729103324591d49bac9f9db875ab7ca8ba6e59a
