### ISSUE TITLE
Change checkbox to a checkmark instead of a solid fill

### ISSUE THREAD

**Issue by jsolly** [jsolly/awesome-django-blog#351]
## Context (What would this enhancement solve that is not possible today?)
It looks kinda weird on the post create page that the checkbox for making the post a draft is a solid fill instead of a checkmark
![image](https://github.com/jsolly/awesome-django-blog/assets/9572232/6a157779-dc7e-42e1-8e48-1cc8ea05b797)

## Ideal solution (What would you like to see implemented?)
This is how bootstrap does it. We should try to emulate this functionality
![image](https://github.com/jsolly/awesome-django-blog/assets/9572232/b1ee7d82-3480-4cd2-aa58-79b62685033d)

**Comment by freedompraise** [comment]
@jsolly , I'm having issues working on this cos I can't access the post-create page. The link was removed from the navbar

**Comment by freedompraise** [comment]
> @jsolly , I'm having issues working on this cos I can't access the post-create page. The link was removed from the navbar

I also tried accessing the page by typing it manually in the browser, but I'm forbidden access

**Comment by jsolly** [comment]
You have to be logged in. If you run the latest migrations, there should be an account admin/admin

**Comment by freedompraise** [comment]
Despite implementing various recommended solutions, the checkbox styling remains non-functional

The following steps were taken to address this issue:

- Utilization of custom CSS and HTML adjustments in accordance with recommended guidelines.
- Attempting multiple rendering approaches for the 'draft' field individually and in conjunction with other form fields.
- Exploring Django's form rendering capabilities while targeting the 'draft' field for customized styling.

**Comment by jsolly** [comment]
@freedompraise there was some dumb CSS styling that I put on it when I was migrating away from Bootstrap awhile back.

Fixed in https://github.com/jsolly/awesome-django-blog/commit/946f9cd90f3ce066b46be05a4aebb644cc18124a

![image](https://github.com/jsolly/awesome-django-blog/assets/9572232/b0096244-367b-48b0-ad9e-e334cec5fdd2)

**Comment by freedompraise** [comment]
> @freedompraise there was some dumb CSS styling that I put on it when I was migrating away from Bootstrap awhile back.
> 
> Fixed in https://github.com/jsolly/awesome-django-blog/commit/946f9cd90f3ce066b46be05a4aebb644cc18124a
> 
> ![image](https://github.com/jsolly/awesome-django-blog/assets/9572232/b0096244-367b-48b0-ad9e-e334cec5fdd2)
> 

Ohhh.
Knew something was wrong somewhere 🤣
