### ISSUE TITLE
Intelligently choose related posts for post-detail page

### ISSUE THREAD

**Issue by jsolly** [jsolly/awesome-django-blog#368]
## Context (What would this enhancement solve that is not possible today?)
Currently the related posts on the post-detail page are fetched like this:
```py
        related_posts = Post.objects.filter(category=category).exclude(
            slug=self.object.slug
        )[:3]
```
This is not ideal because it's just grabing three posts that are in the same category. Furthermore, the three posts are at the beginning of the category, so every post in a given category has the same related posts.

The point of the related posts tool is to point the user to posts that are more related than just in the same category.

## Ideal solution (What would you like to see implemented?)
The way many people would approach this is to use a tag system where posts that are within a certain category also leverage tags to further categorize posts. 

I think we should just compare the snippets of the current posts to the snippets in every other posts. This wouldn't scale to millions of posts, but it definitely will for a few hundred posts. Here's a rough example how it might work. We vectorize the snippets and then calculate their cosine similarities. A lot like how you would do RAG for an AI.

```py
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

def get_top_3_similar_posts(current_post_snippet, all_post_snippets):
    # Include the current post snippet at the start for vectorization
    snippets = [current_post_snippet] + all_post_snippets

    # Convert snippets to TF-IDF vectors
    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform(snippets)

    # Compute cosine similarity of the current post with all others
    cosine_similarities = linear_kernel(tfidf_matrix[0:1], tfidf_matrix).flatten()

    # Get indices of the top 3 most similar posts (excluding the first one which is the current post itself)
    related_post_indices = cosine_similarities.argsort()[-4:-1][::-1]

    # Return the top 3 most similar post snippets
    return [all_post_snippets[i-1] for i in related_post_indices]

# Test the function
current_post_snippet = "your current post's snippet here"
all_post_snippets = ["list of", "other post's snippets", "..."]

top_3_similar = get_top_3_similar_posts(current_post_snippet, all_post_snippets)
```
### Related issues
[Migrate to Vector database for embeddings](https://github.com/jsolly/awesome-django-blog/issues/319)

**Comment by freedompraise** [comment]
Can we looking into using the Django taggit module?

I'm guessing it would be easier to implement.
I've seen a few repos where it was used

**Comment by jsolly** [comment]
It looks like [Taggit](https://django-taggit.readthedocs.io/en/latest/getting_started.html) is something that automatically generates tags. Neat.

I am open to using it. Feel free to start a PR if you'd like!

Here are my questions:
1 - Should we allow authors to make their own tags or will taggit handle all the tagging? If we allow author-chosen tags, will need to add it to the Post form.
2 - Will tags be updated when posts are updated with more/less tags. For example, if I completely re-write an article, will tags be automatically removed/added based on the new content?
3 - How will these tags be used to choose 'related posts' for any given post.

**Comment by freedompraise** [comment]
By default, django-taggit allows users to create their own tags. You can integrate this into your Post form easily.

By default, django-taggit handles updating tags based on the new content of the post when it's edited.
If you update the content or make changes to tags within the Post model and save it, django-taggit will automatically manage the tags.

To choose related posts based on tags, you can define a method in your Post model that fetches related posts based on shared tags.
The method could use the tags of the current post to filter related posts.

The challenge would be with generating tags for already existing posts. 
I think I'd still have to use sklearn

**Comment by jsolly** [comment]
I'll take a look at this one.

**Comment by freedompraise** [comment]
Alright. I'd push what I have been working on

**Comment by freedompraise** [comment]
To combine the logic for generating tags from post content using sk-learn with `taggit` for assigning tags to already existing posts, this should work:

  - Use the logic with scikit-learn to generate tags for existing post content. Modify the `generate_tags_from_content` function to return the top N tags.

  - Iterate through your existing posts.
  - For each post, get its content and using a function to generate tags from content` function to generate tags.
  - Assign these generated tags to the respective post using `taggit`.

**Comment by jsolly** [comment]
@freedompraise feel free to put it on a branch. I can take it from there =]

**Comment by freedompraise** [comment]
> @freedompraise feel free to put it on a branch. I can take it from there =]

I've pushed it

**Comment by freedompraise** [comment]
> > @freedompraise feel free to put it on a branch. I can take it from there =]
> 
> I've pushed it

oops. I have an error to resolve

**Comment by freedompraise** [comment]
@jsolly . I've resolved the errors. You can take on from here

**Comment by jsolly** [comment]
@freedompraise I did start to go down the road of Django taggit, but I think I want to take this another direction similar to how I originally wrote the description. Here's my vision for this feature

Here is a [conversation I had with ChatGPT about it.](https://chat.openai.com/share/823e6d4a-ce29-45e3-b75b-f2555a9ecd72)

Essentially, we store the cosine similarities of each post and store these in a Django model.

A background task will kick off whenever a post is saved that re-calculates similarities.

On the post-detail page, the three related posts have the top cosine similarities to the current post.

I think this is a lot better than having the overhead of creating tags and adding them to posts. I want this to be mostly 'automagic' where the post author doesn't have to think too much about how to relate different posts to each other.

Will be working on a new PR and let you know how it goes!

**Comment by jsolly** [comment]
Completed. 

Related posts are now fetched based on cosine similarity
