### ISSUE TITLE
Match related posts UI/UX to post cards

### ISSUE THREAD

**Issue by jsolly** [jsolly/awesome-django-blog#371]
## Context

Currently, the related posts don't look great in dark mode.
![2023-10-09_20-14-41 (1)](https://github.com/jsolly/awesome-django-blog/assets/9572232/ffd007b6-4f8e-4045-b0e3-6d317250f2fd)

## Ideal solution

It should look like this:
![2023-10-09_20-15-47 (1)](https://github.com/jsolly/awesome-django-blog/assets/9572232/41a3cac5-2bac-44ab-9f45-96612e281912)

## Additional context and related issues
We'll have to match the CSS animations and colors. So instead of them just being applied to post cards, they also apply to the realted post cards on the post detail page.

**Comment by jsolly** [comment]
@freedompraise want to take a stab at this?

**Comment by freedompraise** [comment]
> @freedompraise want to take a stab at this?

I cant see the image under `Ideal Solution`. Guessing it's a GitHub issue

**Comment by jsolly** [comment]
@freedompraise here is a direct link to the GIF
https://www.screencast.com/t/QUlZNGCH

**Comment by freedompraise** [comment]
> @freedompraise here is a [direct link](https://www.screencast.com/t/QUlZNGCH) to the GIF

aiit
