### ISSUE TITLE
Redundant Category Navigation

### ISSUE THREAD

**Issue by freedompraise** [jsolly/awesome-django-blog#389]
## Context
There are double navigation options for the blog categories, and I feel there would be a more creative option

### What's your idea to make it better?
I understand that the bar at the left enables easy navigation and consistent styling of the page, and the one at the navbar is useful for smaller screens where the navigation at the side would not be displayed. 
I suggest hiding the one at the navbar for bigger screens

### Screenshots
![Uncategorized _ Blogthedata com and 4 more pages - Personal - Microsoft​ Edge 09_12_2023 10_25_16](https://github.com/jsolly/awesome-django-blog/assets/70984186/6702c3c8-b3ba-4bc6-a2da-668872549c63)

### Record

- [x] I have read the Contributing Guidelines
- [x] I have searched the issues for a similar request
- [x] I want to work on this issue

**Comment by freedompraise** [comment]
I've reviewed this issue and I want to implement the suggested changes.

Can I go ahead? @jsolly

**Comment by jsolly** [comment]
Go for it!

**Comment by freedompraise** [comment]
Aiit

**Comment by jsolly** [comment]
Looks good. Thanks!
