### ISSUE TITLE
Improve related post relevance

### ISSUE THREAD

**Issue by jsolly** [jsolly/awesome-django-blog#396]
## Context

We currently use cosine similarity to decide which posts are related to other posts. It has the following limitations.

1 - Cosine similarities are not recalculated when a post is added or updated (the added or edited post is, but not every other post)
2- The posts are not 'chunked' resulting in cosine similarities are thrown off with long and short posts being compared to each other

## Ideal solution

To address (1), cosign similarities should be re-calculated for all posts when a new post is added or removed. It's overkill to recalculate everything if a blog post is updated.

Posts should be chunked to address (2), and the chunks should be compared instead of the whole post.

**Comment by freedompraise** [comment]
@jsolly you worked on this some time ago, right?

**Comment by jsolly** [comment]
Yeah, I added an implementation that needs to be improved. If you want to give it a try, go ahead. If not, I am not sure when I will get around to it.

**Comment by freedompraise** [comment]
Okay. I'd just close the issue then
