### ISSUE TITLE
Update Ezra Chat Bot styling

### ISSUE THREAD

**Issue by freedompraise** [jsolly/awesome-django-blog#406]
## Context

The current UI is a bit crappy and doesn't do well in responsiveness. Also, its black background colour blends into the main background of the site ((prior to prompting) which doesn't look good. 

### What's your idea to make it better?
Update the UI to something sleek and responsive

### Record

- [x] I have read the Contributing Guidelines
- [x] I have searched the issues for a similar request
- [x] I want to work on this issue

**Comment by jsolly** [comment]
Good idea. All of the CSS for Ezra has a specific section in the main.css.

The chatbot uses a combination of vanilla JS and HTMX, so be on the lookout for that.

I made a 1 hour video about how I created the bot that might be useful as a reference: https://youtu.be/4EYe4-tpRVY?si=inTga6eMqhBjchny

**Comment by freedompraise** [comment]
> Good idea. All of the CSS for Ezra has a specific section in the main.css.
> 
> The chatbot uses a combination of vanilla JS and HTMX, so be on the lookout for that.
> 
> I made a 1 hour video about how I created the bot that might be useful as a reference: https://youtu.be/4EYe4-tpRVY?si=inTga6eMqhBjchny

Okay

I will pick up this issue now

**Comment by jsolly** [comment]
I really like the styling the [ring.com](https://ring.com/) uses for their chat. Maybe borrow inspiration from them.

![CleanShot 2024-04-30 at 21 45 17](https://github.com/jsolly/awesome-django-blog/assets/9572232/c5a0c760-7fe9-41ed-ba29-c7f811493a16)

**Comment by freedompraise** [comment]
> I really like the styling the [ring.com](https://ring.com/) uses for their chat. Maybe borrow inspiration from them.
> 
> ![CleanShot 2024-04-30 at 21 45 17](https://github.com/jsolly/awesome-django-blog/assets/9572232/c5a0c760-7fe9-41ed-ba29-c7f811493a16)
> 

Okay cool. I've been in need of inspiration this whole time😅

**Comment by freedompraise** [comment]
Man, I've never procratinated a task this much, ever!😂
It's been on my todoist for like a month.
Let me start working on it already😂

**Comment by freedompraise** [comment]
> Good idea. All of the CSS for Ezra has a specific section in the main.css.
> 
> The chatbot uses a combination of vanilla JS and HTMX, so be on the lookout for that.
> 
> I made a 1 hour video about how I created the bot that might be useful as a reference: https://youtu.be/4EYe4-tpRVY?si=inTga6eMqhBjchny

I find it intriguing that there's vanilla JS here😅.
You made me believe it was forbidden for the project when I was implementing the comment functionality with htmx

**Comment by freedompraise** [comment]
@jsolly I'm having issues with updating the styling here.

Changes in the styling aren't reflecting on the site

**Comment by jsolly** [comment]
@freedompraise how are you running the app? Can you try this command?

`python3 app/manage.py livereload`

If that doesn't work, you might want to try going into the network tab and checking 'disable cache'

<img width="708" alt="Screenshot 2024-06-02 at 8 13 25 AM" src="https://github.com/jsolly/awesome-django-blog/assets/9572232/e3264636-bf2a-453c-8632-b089e96512e7">

**Comment by freedompraise** [comment]
I've checked the 'disable cache', and it isn't working.

The command to run with livereload returns this error: `CommandError: "livereload" is not a valid port number or address:port pair.
(venv) `

**Comment by jsolly** [comment]
I was wrong in how livereload works. I just pushed a change. Can you try this?

1 - Add LIVERELOAD=True to your .env file
2 - Run these two commands in TWO different terminal windows
```
python3 app/manage.py runserver
```

```
python3 app/manage.py livereload
```

Make sure the runserver command is run before the livereload.

3 - Make a CSS change.
It should be reflected in the app immediately.

**Comment by freedompraise** [comment]
> I was wrong in how livereload works. I just pushed a change. Can you try this?
> 
> 1 - Add LIVERELOAD=True to your .env file 2 - Run these two commands in TWO different terminal windows
> 
> ```
> python3 app/manage.py runserver
> ```
> 
> ```
> python3 app/manage.py livereload
> ```
> 
> Make sure the runserver command is run before the livereload.
> 
> 3 - Make a CSS change. It should be reflected in the app immediately.
okay

**Comment by freedompraise** [comment]
It returns this error:
`
$ python app/manage.py livereload
Unknown command: 'livereload'
Type 'manage.py help' for usage.
(venv) 
`

**Comment by jsolly** [comment]
@freedompraise please make sure you add `LIVERELOAD=True` to your .env file. If you don't do that, you get the error you are mentioning.

**Comment by freedompraise** [comment]
It's working fine

**Comment by freedompraise** [comment]
@jsolly  I still am not observing any changes. Could it be because I'm working on the staticfiles folder?

**Comment by jsolly** [comment]
Weird. Can we take a look together in a call? Also fun to catch up =]

Find a slot on my calendar!

https://cal.com/jsolly/coffee-chat

**Comment by freedompraise** [comment]
Alright!

**Comment by jsolly** [comment]
Hey @freedompraise I see the branch is still open. Do you need any more help?

I am pretty sure we got all the livereloading stuff working in our call.

**Comment by freedompraise** [comment]
Hello John. I encountered some styling conflicts earlier, and struggled to center a few divs😪

I am back on it now.

Made some changes earlier, and should make the PR today
