### ISSUE TITLE
problems getting started with awesome-django-blog under vscode

### ISSUE THREAD

**Issue by dmccallie** [jsolly/awesome-django-blog#426]
Hello @jsolly - I am experimenting with your nice `awesome-django-blog` to consider it as a starting point for a project I have.  But I am running into some problems getting started. I'm sure I am doing something dumb, and would appreciate a pointer!

Context: WSL2 / Ubuntu. 

I cloned the project and followed the instructions on the github code page, and was able to get the blog running, albeit with a few errors that went away after I performed the `import posts` utility.  So perhaps that is not an optional step?

I then discovered that the pages were displaying very slowly, which appears to be due to missing `live_reload.js` file (timeouts.)  This was occurring when I was running `python app/manage.py runserver` from a stand alone terminal shell.

So I tried running the app from a terminal opened inside vscode, but I continually get the error:
 `ModuleNotFoundError: No module named '"app'`

I have properly activated the venv and verified that it is active. The vscode terminal is open to the base directory of the project  (`awesome-django-blog`) which was created in the initial instructions.

I also created a `.env` file that contains `DJANGO_SETTINGS_MODULE="app.settings.dev"` as well as `USE_SQLITE=True`

What am I missing to get the code to run from within a vscode terminal, and how to I address the missing `live_reload.js` file? It appears that somehow I need to start the `live_reload` server but I don't see instructions on how to do that? 

Sorry for the naive questions, but thanks for your help. I am looking forward to diving deeper into the project.

David

**Comment by jsolly** [comment]
Hi there! This was happening due to there being comments in the example .env file.

I added a new command `python app/manage.py setup_env` that will re-create the correct .env file from `.env.example`

Could you try deleting your existing `.env` file, run that command, and then see if the migrate command works?

I updated the install instructions in the README with the new workflow.

Hope that works for you! I think it will also fix the livereload issue, but let me know if it doesn't.

**Comment by dmccallie** [comment]
Hi John,

The code you added fixed the "ModuleNotFoundError".  Apparently the .env file cannot have comments nor can it tolerate spaces before and after the equals sign.  Thanks!

However, I am still running into problems with  **`livereload.js` timing out,** making the page fetches slow, while it waits for the timeout.  When I run `python3 app/manage.py runserver` I now see:

`
INFO 2024-05-22 21:27:42,498 django.utils.autoreload autoreload autoreload.py 668 run_with_reloader Watching for file changes with StatReloader
`

which was not running before your recent fix, but unfortunately it still times out waiting for livereload.js?


Also, I am getting this error (and a chain of similar errors repeating) when accessing the home page the first time (and subsequent times):
```
DEBUG 2024-05-22 21:30:19,714 django.template base base.py 925 _resolve_lookup Exception while resolving variable 'post' in template 'blog/home.html'.
Traceback (most recent call last):
  File "/home/david/python_projects/awesome-django-blog/.venv/lib/python3.10/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
  File "/home/david/python_projects/awesome-django-blog/.venv/lib/python3.10/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'post'

(... repeats ...)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/python_projects/awesome-django-blog/.venv/lib/python3.10/site-packages/django/template/base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'post'
```
Suggestions?
Thanks for your help.

**Comment by jsolly** [comment]
Thank you so much for the detailed info. I think I have resolved both of these issues!

For the timing out livereload one, I added [conditional logic](https://github.com/jsolly/awesome-django-blog/commit/e4911acca8ea19e04d86a3d0e9b23c345bcbe9dd) to only inject the livereload script if you are starting the app with `python3 app/manage.py runserver livereload` 

You can learn more about Django Livereload [on their Github Repo](https://github.com/tjwalch/django-livereload-server).

I [changed the default logging level from DEBUG to INFO](https://github.com/jsolly/awesome-django-blog/commit/fada724120343b2f4c966ae0b693c751850ede22) for the template error. You can normally ignore these errors unless something is breaking. I tried to trace it down, but couldn't find it.

Note the following snippet from the [Django docs](https://docs.djangoproject.com/en/5.0/ref/logging/#django-template):
> django.template[¶](https://docs.djangoproject.com/en/5.0/ref/logging/#django-template)
Log messages related to the rendering of templates.
Missing context variables are logged as DEBUG messages.

Please pull again and hopefully that clears everything up = )

**Comment by dmccallie** [comment]
Hi John,

Those changes fixed the livereload problem (I am just not using it for now though.)
I have a few new issues, but I will close this issue and start a new one.
Thanks again for the quick responses.
