### ISSUE TITLE
Meta image alt text is required even if no image is added

### ISSUE THREAD

**Issue by dmccallie** [jsolly/awesome-django-blog#431]
You may not be interested in these little issues, but it appears that `metaimg_alt_txt` is required on creation of a new post, even if there is no meta image.

This may be the desired behavior, but it surprised me.

**Comment by jsolly** [comment]
All posts come with the default metaimg that's why alt text is always present.

```py
    # blog.models.Post
    metaimg = ResizedImageField(
        force_format="WEBP",
        quality=75,
        upload_to="post_metaimgs/",
        default="default.webp",
    )
    metaimg_alt_txt = models.CharField(max_length=500, default="John Solly Headshot")
```
