### ISSUE TITLE
how are you serving media files?

### ISSUE THREAD

**Issue by dmccallie** [jsolly/awesome-django-blog#434]
Hi @jsolly ,

As a django beginner, I decided to build my own super-simple blog service as a way to learn django rather than just clone your example.  I learn better by learning bottom up.  However, I have learned a huge amount just from reading your source code, and trying to understand how it works.

I have a question, if you have a moment.  How are you serving your `/media` files when not running in `DEBUG=True` mode?  Based on the Dockerfile and docker-compose files, it looks like you are running production (?) using the standard `python manage.py runserver` command rather than using `gunicorn` and `nginx`?  I see that you are using `whitenoise` to serve your `/static/` files, but I can't figure out how you are getting the standard `runserver` to serve `/media/` files when not in debug?

What am I missing? 

Thank you again for sharing your code.

**Comment by jsolly** [comment]
Hey @dmccallie !

Apologies for this being super confusing. I got about halfway through migrating the deployment to use Docker but stopped halfway through.

I just pushed [this commit](https://github.com/jsolly/awesome-django-blog/commit/a8883f6beaf18911dfc4b5d804d27cc35cb6c8a0) that removes all the docker stuff that wasn't being used.

I am using gunicorn and nginx. If you follow [this guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu), you can duplicate my environment.

If you do end up doing that, it would be very useful if you could help re-write the prod deploy docs = )

Here are two documents that I think cover MOST* of the configuration
https://github.com/jsolly/awesome-django-blog/blob/master/docs/PROD_DEPLOY.md
https://github.com/jsolly/awesome-django-blog/blob/master/docs/PROD_DEPLOY2.md

Unfortunately, I never did a perfect job documenting how I set things up in Prod.

**Comment by jsolly** [comment]
Specifically, here is an nginx file that outlines how the media files are served
https://github.com/jsolly/awesome-django-blog/blob/master/config/nginx/app

I believe all instances of 'django_project' are now renamed to 'app'
